"""add_cascade_delete_faces

Revision ID: 67743383a8f2
Revises: cfaffc97d402
Create Date: 2026-02-22 00:07:48.027492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67743383a8f2'
down_revision: Union[str, Sequence[str], None] = 'cfaffc97d402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('faces_user_id_fkey'), 'faces', type_='foreignkey')
    op.create_foreign_key(None, 'faces', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faces', type_='foreignkey')
    op.create_foreign_key(op.f('faces_user_id_fkey'), 'faces', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
