"""Changing relationship between user and faces from one to one to one to many

Revision ID: 94f0198d433f
Revises: fc7333bafe32
Create Date: 2026-02-03 01:29:34.528175

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '94f0198d433f'
down_revision: Union[str, Sequence[str], None] = 'fc7333bafe32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('faces_user_id_key'), 'faces', type_='unique')
    op.alter_column('faces', 'embeddings', new_column_name='embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.alter_column('faces', 'embedding', new_column_name='embeddings')
    op.create_unique_constraint(op.f('faces_user_id_key'), 'faces', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
