"""Add Detection Confidence Score to the Face Table

Revision ID: dbd84ae9a59a
Revises: 94f0198d433f
Create Date: 2026-02-08 03:59:47.646536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd84ae9a59a'
down_revision: Union[str, Sequence[str], None] = '94f0198d433f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faces', sa.Column('detection_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faces', 'detection_score')
    # ### end Alembic commands ###
