"""create users table

Revision ID: fc7333bafe32
Revises: 
Create Date: 2026-01-30 06:25:34.450902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc7333bafe32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('faces', sa.Column('face_id', sa.UUID(), nullable=False))
    op.add_column('faces', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('faces', sa.Column('embeddings', sa.ARRAY(sa.Float()), nullable=False))
    op.create_unique_constraint(None, 'faces', ['user_id'])
    op.create_foreign_key(None, 'faces', 'users', ['user_id'], ['user_id'])
    op.drop_column('faces', 'name')
    op.drop_column('faces', 'embedding')
    op.drop_column('faces', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faces', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('faces', sa.Column('embedding', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False))
    op.add_column('faces', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'faces', type_='foreignkey')
    op.drop_constraint(None, 'faces', type_='unique')
    op.drop_column('faces', 'embeddings')
    op.drop_column('faces', 'user_id')
    op.drop_column('faces', 'face_id')
    op.drop_table('users')
    # ### end Alembic commands ###
